### ISSUE TITLE
feat: NixOS on BTRFS (with Swap, Hibernate support)

### ISSUE THREAD

**Issue by seungwoo-lee-518** [seungwoo-lee-518/dotfiles#19]
# feat: NixOS on BTRFS (with Swap, Hibernate support)

## Why?

* NixOS GUI Installer breaks on Mounting swap.
* https://discourse.nixos.org/t/how-to-deal-with-swap-failed-on-nixos-gui-installer/47628
* There are ongoing PR to solve this issue, but seems like it cannot be merged immediately.
* https://github.com/NixOS/calamares-nixos-extensions/pull/36

## TODOs

- [ ] Write a disk configuration using [disko](https://github.com/nix-community/disko)
    - BTRFS
- [ ] Find a way to enable `swap`:
    - https://sawyershepherd.org/post/hibernating-to-an-encrypted-swapfile-on-btrfs-with-nixos/
    - Seems like Referenced arch wiki is updated to support to find swap file offset using: `btrfs inspect-internal map-swapfile`
    - https://wiki.archlinux.org/title/Power_management/Suspend_and_hibernate#Acquire_swap_file_offset
- [ ] write full nixos configuration to `/etc/nixos/configuration.nix`
    - See, https://github.com/NixOS/calamares-nixos-extensions
